### ISSUE TITLE
Errors related to buildModule

### ISSUE THREAD

**Issue by captaindav** [druxt/druxt-entity#104] opened 2021-05-26 15:28 UTC
**Describe the bug**
I get a serve runtime error when I add druxt-entity to buildModules array.  I have also tried @druxt/druxt-entity which gives a different error I believe.

Here is my index.vue file:
https://github.com/captaindav/vue-outline/blob/master/packages/outline/pages/index.vue 

Here is my buildModules, please see last line:

  buildModules: [
    // https://go.nuxtjs.dev/eslint
    //'@nuxtjs/eslint-module',
    // https://go.nuxtjs.dev/vuetify
    '@nuxtjs/vuetify',
    // https://github.com/nuxt-community/apollo-module
    '@nuxtjs/apollo',
    // https://composition-api.nuxtjs.org/
    '@nuxtjs/composition-api/module',
    // https://druxtjs.org/
    'druxt',
    'druxt-entity'
  ],

**To Reproduce**

Use buildModules as above.

**Expected behavior**
Vue app wil run without error.

**Your Environment (please complete the following information):**
 - Device: MacBook Pro
 - OS: IOS
 - Browser  chrome
 - Version latest

What is the correct syntax to add druxt-entity to buildModules?

**Comment by suit4** [comment] 2021-05-26 16:11
Same here:
```
modules: [
    // https://go.nuxtjs.dev/axios
    '@nuxtjs/axios',
    // https://go.nuxtjs.dev/pwa
    '@nuxtjs/pwa',
    // https://go.nuxtjs.dev/content
    '@nuxt/content',
    // https://i18n.nuxtjs.org/
    // 'nuxt-i18n',
    // https://druxtjs.org/
    'druxt',
    'druxt-entity',
    'druxt-menu',
  ],

```  
**Expected behavior**
Vue app wil build without error or at least give some error message.

**Your Environment (please complete the following information):**
Device: MacBook Pro
OS: BigSur latest
Browser: Brave / Chrome latest

**Comment by Decipher** [comment] 2021-05-27 21:35
Hi @captaindav,

Druxt modules are regular `modules`, not `buildModules`, which is likely the cause of the initial errors.

Druxt Schema can be long, as it builds a static version of the schema file in the Nuxt build artefacts each time you initiate the build. You can filter the generated schemas to only those you need by setting `druxt.schema.filter` in your `nuxt.config.js`: https://github.com/druxt/druxt-schema#usage

**Comment by Decipher** [comment] 2021-08-14 06:12
Hi @captaindav,

I'm closing this issue but I'm not certain if it was solved.

If you are still having the issue, please re-open an issue in the https://github.com/druxt/druxt.js mono-repo.

**Closed by Decipher** 2021-08-14 06:12 UTC
